language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r intellij_springboot_webservice01 *
  - mkdir -p deploy
  - mv intellij_springboot_webservice01.zip deploy/intellij_springboot_webservice01.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY

    bucket: freelec-gihang-springboot-build #S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로 설정
    local_dir: deploy #before deploy 에서 생성한 디랙토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: freelec-gihang-springboot-build #S3버킷
    key: intellij_springboot_webservice01.zip #빌드 파일을 압축해서 전달
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployes: true

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - abc1775@naver.com
